import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    position: 'absolute',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
  },
  title_wrapper: {
    width: 330,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '85%',
    marginLeft: '8%',
    marginBottom: 100,
    alignSelf: 'flex-start',
  },
  top_title: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: 3.55,
    textTransform: 'uppercase',
    color: '#030303',
  },
  bottom_title: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: 'bold',
    color: '#C63131',
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: 2.25,
    textTransform: 'uppercase',
    marginBottom: 16,
    marginLeft: '-31%',
  },
  subtitle_wrapper: {
    // marginLeft: '2%',
  },
  subtitle: {
    fontFamily: 'SF Pro Display',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 22,
    color: '#929292',
  },
  button_wrapper: {
    width: 321,
    height: 45,
    justifyContent: 'flex-end',
  },
  button: {
    borderColor: 'rgba(0, 0, 0, 0.54)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 29,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 10,
  },
  button_content: {
    fontFamily: 'SF Pro Display',
    marginLeft: 9,
    color: 'rgba(0, 0, 0, 0.54)',
    letterSpacing: 0.25,
  },
});
